### ISSUE TITLE
Typo in splash screen image

### ISSUE THREAD

**Issue by minna-xD** [SankethBK/diaryvault#107]
The image `assets/images/splash_screen.png` has a typo in the app name. It says "Dairy Vault" instead of "Diary Vault"

![splash_screen](https://github.com/SankethBK/diaryvault/assets/44906587/aeec22f8-9c1a-400a-8a4b-b005b23b53ba)

**Comment by ayato91** [comment]
@SankethBK  I have created similar logo fixing the typo. Can I make a pull request?
