### ISSUE TITLE
Add new themes

### ISSUE THREAD

**Issue by SankethBK** [SankethBK/diaryvault#13]
Refer the documentation of [themes](https://github.com/SankethBK/diaryvault/blob/master/docs.md#theming). 

To add a new theme
* Decide if it's a dark theme or a light theme.
* Prepare a background image and a color palette that matches / compliments colors in the background image. 
* If it's light theme, most of the colors from `lib/app/themes/coral_bubble_theme.dart` can be reused. If its a dark theme, most of the colors from `lib/app/themes/cosmic_theme.dart` can be re-used 

Start by altering the background image and colors of any existing theme, when its finalized create a new class in `lib/app/themes/theme_extensions`. 

Reference PR for adding a new theme: https://github.com/SankethBK/diaryvault/pull/36

**Comment by soam1** [comment]
@SankethBK  would love to do that.

**Comment by SankethBK** [comment]
@soam1 Sure, you can use this [PR](https://github.com/SankethBK/diaryvault/pull/36) as reference for adding new themes

**Comment by ayato91** [comment]
@SankethBK I would like to contribute here :)

**Comment by SankethBK** [comment]
Sure @ayato91

**Comment by vijaymehrotra** [comment]
Hello @SankethBK ,
I want to contribute to this

**Comment by SankethBK** [comment]
Sure @vijaymehrotra

**Comment by PratyushChauhan** [comment]
Is anyone working on this?

**Comment by SankethBK** [comment]
@PratyushChauhan Multiple folks can work on this issue, since everyone will be creating their own theme. Feel free to pick it up and get creative with your unique ideas.

**Comment by Redvey** [comment]
Hello I would also love to work on this

**Comment by SankethBK** [comment]
@Redvey sure

**Comment by Redvey** [comment]
@SankethBK Hey, I have made a PR that is adding a Dark Academia theme to the app, please do review.

**Comment by TikuGaelle** [comment]
Hello @SankethBK 
I would like to work on this issue.

**Comment by SankethBK** [comment]
@TikuGaelle sure, go ahead

**Comment by TikuGaelle** [comment]
Hello @SankethBK I have been trying to run  the app for some day now but always get the errors below, please have any idea on how to resolve them?

`Launching lib\main.dart on AOSP on IA Emulator in debug mode...
packages/flutter_quill/lib/src/widgets/raw_editor.dart:283:7: Error: The non-abstract class 'RawEditorState' is missing implementations for these members:
 - TextSelectionDelegate.lookUpEnabled
 - TextSelectionDelegate.searchWebEnabled
 - TextSelectionDelegate.shareEnabled
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class RawEditorState extends EditorState
      ^^^^^^^^^^^^^^
../../../flutter/packages/flutter/lib/src/services/text_input.dart:1051:12: Context: 'TextSelectionDelegate.lookUpEnabled' is defined here.
  bool get lookUpEnabled => true;
           ^^^^^^^^^^^^^
../../../flutter/packages/flutter/lib/src/services/text_input.dart:1054:12: Context: 'TextSelectionDelegate.searchWebEnabled' is defined here.
  bool get searchWebEnabled => true;
           ^^^^^^^^^^^^^^^^
../../../flutter/packages/flutter/lib/src/services/text_input.dart:1057:12: Context: 'TextSelectionDelegate.shareEnabled' is defined here.
  bool get shareEnabled => true;
           ^^^^^^^^^^^^
packages/flutter_quill/lib/src/widgets/raw_editor.dart:351:47: Error: Required named parameter 'onLookUp' must be provided.
    return EditableText.getEditableButtonItems(
                                              ^
../../../flutter/packages/flutter/lib/src/widgets/editable_text.dart:1867:38: Context: Found this candidate, but the arguments don't match.
  static List<ContextMenuButtonItem> getEditableButtonItems({
                                     ^^^^^^^^^^^^^^^^^^^^^^
packages/flutter_quill/lib/src/widgets/quill_single_child_scroll_view.dart:289:18: Error: The method '_RenderSingleChildViewport.getOffsetToReveal' has fewer named arguments than those of overridden method 'RenderAbstractViewport.getOffsetToReveal'.
  RevealedOffset getOffsetToReveal(RenderObject target, double alignment,
                 ^
../../../flutter/packages/flutter/lib/src/rendering/viewport.dart:126:18: Context: This is the overridden method ('getOffsetToReveal').
  RevealedOffset getOffsetToReveal(
                 ^
packages/flutter_quill/lib/src/widgets/quill_single_child_scroll_view.dart:289:18: Error: The method '_RenderSingleChildViewport.getOffsetToReveal' doesn't have the named parameter 'axis' of overridden method 'RenderAbstractViewport.getOffsetToReveal'.
  RevealedOffset getOffsetToReveal(RenderObject target, double alignment,
                 ^
../../../flutter/packages/flutter/lib/src/rendering/viewport.dart:126:18: Context: This is the overridden method ('getOffsetToReveal').
  RevealedOffset getOffsetToReveal(
                 ^
Target kernel_snapshot failed: Exception


FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\brend\flutter\packages\flutter_tools\gradle\src\main\groovy\flutter.groovy' line: 1350

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\Users\brend\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 29s`

**Comment by SankethBK** [comment]
Hi @TikuGaelle , can you share the Flutter version you're using

**Comment by TikuGaelle** [comment]
3.16.5 channel stable

**Comment by SankethBK** [comment]
Try with `Flutter 3.13.0 • channel stable` some of the packages we're using aren't compatible with 3.16 yet

**Comment by TikuGaelle** [comment]
Okay, thank you

**Comment by Amitkumarkoli** [comment]
hey is this still open? 
I would love to contribute on this?

**Comment by Prakharpan-dey** [comment]
@SankethBK is this issue still up?

**Comment by ayato91** [comment]
Yes @Prakharpan-dey  If you are interested in introducing new theme
