### ISSUE TITLE
Display "Share with friends" option in settings

### ISSUE THREAD

**Issue by SankethBK** [SankethBK/diaryvault#15]
Display "Share with Friends" option in settings page. On clicking it, device should prompt user showing different apps (email, WhatsApp, etc) to share the link. 

Use [share_plus](https://pub.dev/packages/share_plus) package

Link to app: https://play.google.com/store/apps/details?id=me.sankethbk.dairyapp

Similar to this 

https://github.com/SankethBK/diaryvault/assets/51091231/4c054904-761c-40e3-8333-f0358f8a9abc

**Comment by gantanikhilraj** [comment]
Hi @SankethBK , I would like to work on this, please assign this to me.

**Comment by SankethBK** [comment]
Hi @gantanikhilraj , have assigned this to you.

**Comment by SankethBK** [comment]
Updated the screen recording link. Previous link was somehow broken

**Comment by gantanikhilraj** [comment]
@SankethBK , I've created a PR, If you need any changes please let me know.
