### ISSUE TITLE
Running application through `flutter run`

### ISSUE THREAD

**Issue by mbfannan** [SankethBK/diaryvault#153]
Hello, I'd love to contribute to this project, however, every time I attempt to run the application I receive the error messages denoted in the screenshot below. I realize that this is a result of dependency issues from the `pubspec.yaml`. I've been attempting to resolve this for a prolonged time, and I'm wondering if anyone may have faced a similar issue @SankethBK. 

<img width="1217" alt="image" src="https://github.com/SankethBK/diaryvault/assets/122257080/60ee9409-70de-410c-931c-f269d2bf8a34">

**Comment by LujainAlMansoori** [comment]
I have this error too, @SankethBK could you please help

**Comment by SankethBK** [comment]
Hi, can you post the output of `flutter --version` and `flutter doctor -v`

**Comment by mbfannan** [comment]
Sure, here's the output of `flutter --version`

<img width="851" alt="image" src="https://github.com/SankethBK/diaryvault/assets/122257080/5d09a0b9-ab96-4677-8a88-a1411ab73783">


Here's the output of `flutter doctor -v`:

<img width="1080" alt="image" src="https://github.com/SankethBK/diaryvault/assets/122257080/7ec24386-4847-4ae8-8f99-46d882ebe060">

**Comment by SankethBK** [comment]
I am using `3.13.0`, can you downgrade to 3.13.0 once and try
```❯ flutter --version
Flutter 3.13.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision efbf63d9c6 (3 months ago) • 2023-08-15 21:05:06 -0500
Engine • revision 1ac611c64e
Tools • Dart 3.1.0 • DevTools 2.25.0
```


Meanwhile, I'll try to migrate it to `3.16.0`

**Comment by mbfannan** [comment]
Ya sure Ill try that out

**Comment by mbfannan** [comment]
It worked by downgrading to version `3.13.0`. To resolve this I went to the flutter folder cloned from the flutter repo. Upon which I ran:

1.  `git fetch --tags`
2. `git checkout 3.13.0`
3. Then run: `flutter --version`
