### ISSUE TITLE
Fix fingerprint login glitch

### ISSUE THREAD

**Issue by SankethBK** [SankethBK/diaryvault#16]
Fingerprint login works, but when app is opened fingerprint login prompt appears, disappears and then appears again. Ideally it should not disappear. Refer to this screen recording at 0:07

[bug.webm](https://github.com/SankethBK/diaryvault/assets/51091231/99bbe5fc-f504-4516-b571-4d17aef39a28)

Fingerprint login is initiated in `AuthPage` widget located at `lib/features/auth/presentation/pages/auth_page.dart`.

This is the line of code starting the fingerprint login

`widget.fingerPrintAuthRepository.startFingerPrintAuthIfNeeded();`

Somehow entire `AuthPage` widget is getting re-rendered, logs might help to debug.

**Comment by droidbg** [comment]
@SankethBK I like to pick this up, can you assign it to me?
