### ISSUE TITLE
Add multi-language support

### ISSUE THREAD

**Issue by SankethBK** [SankethBK/diaryvault#17]
Use `flutter_localizations` / `l10n` for adding multi-language support. Currently hardcoded strings are scattered throughout the app, need to find them and translations.

By default it should use language as device's language. If the device's language is not supported, English should be used.

**Comment by bibekpanda55** [comment]
I can work on this

**Comment by SankethBK** [comment]
Hey @bibekpanda55 , @micedreams is working on this. we have some more open issues, see if you can pick any. You can raise new issues if you find any bug, or have ideas for enhancement or new features

**Comment by micedreams** [comment]
@bibekpanda55 you can take it....

**Comment by SankethBK** [comment]
Sure, assigning this to you @bibekpanda55

**Comment by bibekpanda55** [comment]
Thanks for assigning the issue . Will work on it and create a PR asap.

**Comment by SankethBK** [comment]
@bibekpanda55 you can find the detailed guide here: https://docs.flutter.dev/ui/accessibility-and-localization/internationalization.

For changing language from within the app, i will add more details.

**Comment by bibekpanda55** [comment]
Got it will do

**Comment by SankethBK** [comment]
Adding the steps for reference. 

1. Add `flutter_localizations` and `intl` packages.
2. Add `localizationsDelegates` and add  `Locale('en')` to `supportedLocales` array
3. Create `/lib/l10n` folder at the root of the project. Create `app_en.arb` and extract out all hardcoded strings throughout the code into this file. 
4. Replace hardcoded strings with their corresponding keys from `arb` file

Feel free to join our discord [server](https://discord.gg/84n4aJPg) if you need help with anything

**Comment by bibekpanda55** [comment]
Thanks for the description. Will work on it and get back to you.

**Comment by SankethBK** [comment]
you can fork the repo, make changes to your master branch and raise PR against this repo's master branch. 
> Also there are already a few bugs on the main branch right?
you mean bugs related to setup?

**Comment by SankethBK** [comment]
@bibekpanda55 please confirm if you're working on this

**Comment by bibekpanda55** [comment]
Yes have been busy lately. Will work on it and give you an update by tomorrow

**Comment by SankethBK** [comment]
No worries, thanks for confirming

**Comment by bibekpanda55** [comment]
> you mean bugs related to setup?

Yes some packages are missing like the html,image_picker etc. Should I all that to pubspec.yaml file or what?

**Comment by micedreams** [comment]
> > you mean bugs related to setup?
> 
> Yes some packages are missing from the flutter_quill folder like the html,image_picker etc. Should I all that to pubspec.yaml file or what?

Hi, this feels unrelated to this issue. 
Please raise a new issue.

**Comment by SankethBK** [comment]
Could be because of Flutter version, can you please share the output of `flutter doctor` command

**Comment by SankethBK** [comment]
Those packages are added in `flutter_quill`'s `pubspec.yaml,` we don't need to add them to root folder's `pubspec.yaml`. Let us know If you are facing any issues on running `flutter pub get` and `flutter run`

**Comment by bibekpanda55** [comment]
Flutter doctor doesn't shows any issues . You can check the packages/flutter_quill/flutter_quill_extensions/lib/embeds/toolbar/image_button.dart file for example

**Comment by SankethBK** [comment]
Try running `flutter pub get`, it should install those packages. I don't see any errors in the file you mentioned

**Comment by SankethBK** [comment]
> Flutter doctor doesn't shows any issues 
Can you share the output of `flutter --version`, some packages depend on the Flutter version

**Comment by bibekpanda55** [comment]
I was running pub get on the outside folder , so there were package issues.The issue got resolved after running pub get in the required folder

**Comment by SankethBK** [comment]
Thanks for sharing, we'll add it in setup instructions

**Comment by bibekpanda55** [comment]
Also if you could specify few files or overall folder to extract the raw strings from that would help.

**Comment by SankethBK** [comment]
@bibekpanda55 you can do a global search with this regex `Text\(['|"].*` and exclude the packages/ folder.

<img width="346" alt="image" src="https://github.com/SankethBK/diaryvault/assets/51091231/df1aea8a-b16d-4eb4-a2a2-4bf03506c6ed">

**Comment by bibekpanda55** [comment]
Got it thanks will do

**Comment by bibekpanda55** [comment]
1. Added flutter_localizations and intl packages.
2. Added localizationsDelegates and add Locale('en') to supportedLocales array
3. Created /lib/l10n folder at the root of the project. Create app_en.arb and extracted out all hardcoded strings throughout the code into this file.
4. Replaced hardcoded strings with their corresponding keys from arb file.
Have created a PR for closing this issue. Please check and merge the PR if you don't find any further issues.
