### ISSUE TITLE
Show "share feedback" option in settings

### ISSUE THREAD

**Issue by SankethBK** [SankethBK/diaryvault#18]
An option to share feedback from within the app. 

Add "Share Feedback"  button in settings
<img src="https://github.com/SankethBK/diaryvault/assets/51091231/43486933-7a13-4b07-91a9-8c6130476599" width = "500" />

On clicking it, it should launch email app with subject and sender preconfigured as 
sender: "diaryvault.app@gmail.com"
Subject: "Feedback for diaryvault"

<img src="https://github.com/SankethBK/diaryvault/assets/51091231/d8529b45-1b95-4492-b131-19e79721cede" width = "500" />

This can be `url_launcher` package

```

  final String emailAddress = 'diaryvault.app@gmail.com';
  final String subject = 'Feedback for DiaryVault';

  void _launchEmailApp() async {
    final Uri emailLaunchUri = Uri(
      scheme: 'mailto',
      path: 'diaryvault.app@gmail.com',
      queryParameters: {'subject': 'Feedback for DiaryVault'},
    );```

**Comment by SankethBK** [comment]
Hey @micedreams I changed the description to make it work via email instead of discord bot, as writing discord bot might be difficult. if you have already started working on discord bot we can use same instead of email.

**Comment by micedreams** [comment]
> Hey @micedreams I changed the description to make it work via email instead of discord bot, as writing discord bot might be difficult. if you have already started working on discord bot we can use same instead of email.

I have not started working on it yet... sending it as an email sounds Good!!
