### ISSUE TITLE
Add "tags" support 

### ISSUE THREAD

**Issue by SankethBK** [SankethBK/diaryvault#19]
We need to introduce a new column of type `json` into notes table, which will store all the tags for a note.

We should also support filter by tags eventually.

**Comment by sameer1612** [comment]
Up to take this one.  Assign when available. 

- [ ] Will add tags as csv to sqlite db and write a helper to encode and decode.

- [ ] Will add a text field with autocomplete to enter tags in the diary page.

**Comment by SankethBK** [comment]
Hey @sameer1612 , can you post the detailed approach. If we store it as csv column, will we able to search it via tags?

**Comment by SankethBK** [comment]
Another appraoch would be create a new table with following columns: `note_id` and `tag_name`. This way we would be able to fetch all the tags which can be used for autocompletion, we can also search via tags this way
