### ISSUE TITLE
Message on note delete

### ISSUE THREAD

**Issue by marek-jakub** [SankethBK/diaryvault#193]
The message on note(s) delete is always in English, irrespective of chosen language. Please, refer to screenshots:

![01_delete_note](https://github.com/SankethBK/diaryvault/assets/32166662/5a7b99b1-2d06-4f55-8481-cab2865e7eec)
![02_delete_note](https://github.com/SankethBK/diaryvault/assets/32166662/5dd35adb-1a48-439e-89ff-fbceba55f56d)
![03_delete_note](https://github.com/SankethBK/diaryvault/assets/32166662/f1160ce1-324e-4922-81b7-a5aa88a2457a)

**Comment by SankethBK** [comment]
I'll fix it by next release, thanks for mentioning

**Comment by AliYar-Khan** [comment]
@SankethBK can i work on this?

**Comment by SankethBK** [comment]
@AliYar-Khan sure

**Comment by SankethBK** [comment]
It's 3.13.0

**Comment by AliYar-Khan** [comment]
@SankethBK let me know if there is any problem regarding the translation. I used the Google translator for translating it

**Comment by AliYar-Khan** [comment]
@SankethBK it's been two weeks since I have created the pull request. Let me know when you will be merging it

**Comment by SankethBK** [comment]
Solution: https://github.com/SankethBK/diaryvault/pull/202#discussion_r1577236600
