### ISSUE TITLE
Introduce "todos" within rich text editor

### ISSUE THREAD

**Issue by SankethBK** [SankethBK/diaryvault#20]
An option to add todos from within the note. Flutter quill supports custom embedbuilders. Need to do more research on this.

**Comment by Guillergood** [comment]
I can take this one, do you have some idea or mockup to do so?

**Comment by PratyushChauhan** [comment]
Any updates on this?

**Comment by SankethBK** [comment]
Hi @PratyushChauhan , I need to do a bit more research on how the delta format is parsed in `flutter_quill` to add support for images and videos. I will add more details by mid of this week

**Comment by Prakharpan-dey** [comment]
Are we still working on this? @SankethBK

**Comment by SankethBK** [comment]
Hi. @Prakharpan-dey , this was last year's issue. I will add new issues for this year with more details for this.
