### ISSUE TITLE
Question on permissions

### ISSUE THREAD

**Issue by IzzySoft** [SankethBK/diaryvault#201]
My scanner got a few additional checks last week, so on today's update of your app it reported:

    ! repo/me.sankethbk.dairyapp_2018.apk declares risky permission(s): android.permission.RECORD_AUDIO android.permission.READ_EXTERNAL_STORAGE

May I ask what those permissions are needed for? I could not find a matching feature in the app description (but might simply have missed it). Thanks in advance!

**Comment by SankethBK** [comment]
Hi, I am currently using these permissions
```
<uses-permission android:name="android.permission.USE_FINGERPRINT" />
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
<uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM" />
<uses-permission android:name="android.permission.RECORD_AUDIO" />
```
`RECORD_AUDIO` was added recently, I added a feature for attaching audio files in notes which can be picked from file manager or audio can be recorded from within the app. I am assuming `file_picker` library is using `READ_EXTERNAL_STORAGE` permission, which is used to add images, audio and video to the note

**Comment by IzzySoft** [comment]
Thanks! Yes, an integrated voice recorder totally explains this. And as I meanwhile found out, `READ_EXTERNAL_STORAGE` is needed to access other app's media files until Android 9, so I've added that to the allow-list of your app as well.

All clear then, thanks again!
