### ISSUE TITLE
Save Note Popup displays even when none of the note content is modified

### ISSUE THREAD

**Issue by SankethBK** [SankethBK/diaryvault#211]
When I tap a note and view it, then try to go back it pops up a 'you have unsaved changes' popup. 

ref issue: https://github.com/SankethBK/diaryvault/issues/209

<img width="309" alt="image" src="https://github.com/user-attachments/assets/57c7ee08-061b-40bd-a43b-d7ef3e955a0e">

This is the code used for showing unsaved changes popup in `note_create_page.dart` or `note_read_only_page.dart`, 

```
    return WillPopScope(
      onWillPop: () async {
        bool? result = await showCloseDialog(context);

        if (result == true) {
          notesBloc.add(RefreshNote());
          return true;
        }
        return false;
      },
```

`NotesBloc` stores the state of currently opened note. `NoteInitialState` is the initial state and controller parameter holds the rich text editor's internal state. It will only be transitioned to `NoteUpdatedState` when `title`, `createdAt`, `allNoteAssets` or `tags` is updated.  But if user types something into rich text editor without changing any of these, the state will still remain as NoteInitialState as controller takes care of managing rich text editor's state internally. So there's no way to distinguish if an actual edit has happened in such cases.

Solution: 
When user clicks on back button in `note_create_page.dart` or `note_read_only_page.dart`, retrieve the note from database and compare it with the current note, if its different then only show the popup, otherwise pop the screen.

There are multiple ways for comparing two notes, easiest one can be to compare `hash` property of notes which will be modified if any of the content is changed. Refer `saveNote` method to know how `hash` is updated when a note is changed.

Relevant files:
```
- lib/features/notes/presentation/pages/note_create_page.dart
- lib/features/notes/presentation/pages/note_read_only_page.dart
- lib/features/notes/data/repositories/notes_repository.dart
```

**Comment by malachieborohoul** [comment]
Hi @SankethBK ,  I'd like to contribute to this issue. Is that okay?

**Comment by SankethBK** [comment]
Hi @malachieborohoul , sure

**Comment by malachieborohoul** [comment]
Great, thanks
