### ISSUE TITLE
Replace PNG images in README with WebP 

### ISSUE THREAD

**Issue by SankethBK** [SankethBK/diaryvault#214]
These are the screenshots in README which are in PNG format

```
<div style="display:flex; flex-wrap: wrap;">
  <img src="https://github.com/SankethBK/diaryvault/assets/51091231/3030fcb2-18eb-4fd9-abb5-bb8343524495" style = "padding: 1rem; height: 300px">
  <img src="https://github.com/SankethBK/diaryvault/assets/51091231/d8d8cb28-6eef-4b99-83e9-096d32fa7233" style = "padding: 1rem; height: 300px">
  <img src="https://github.com/SankethBK/diaryvault/assets/51091231/27f90610-9d20-42a3-bc44-09abd5e9d538" style = "padding: 1rem; height: 300px">
  <img src="https://github.com/SankethBK/diaryvault/assets/51091231/b9816cfc-d0f7-4319-b1d2-c737afb7d8d0" style = "padding: 1rem; height: 300px">
  <img src="https://github.com/SankethBK/diaryvault/assets/51091231/5eed68a2-ae46-4c7b-8e10-f2080057cb8d" style = "padding: 1rem; height: 300px">
  <img src="https://github.com/SankethBK/diaryvault/assets/51091231/9f811ef8-35b5-4212-b8a9-5c96444ce4a4" style = "padding: 1rem; height: 300px">
  <img src="https://github.com/SankethBK/diaryvault/assets/51091231/209849ac-e5bc-4b5d-ac5f-c6f4afd72dcb" style = "padding: 1rem; height: 300px">
  <img src="https://github.com/SankethBK/diaryvault/assets/51091231/adb2ee90-8097-40ba-9f37-eee7d4a708fc" style = "padding: 1rem; height: 300px">
</div>
```

They take long time to render, so we need to convert them to WebP to reduce image size, thus render time. You can open these Urls, download the images, convert them to webp and paste the updated images. 

You can use https://cloudconvert.com/png-to-webp for conversion.

**Comment by cleobnvntra** [comment]
Hi @SankethBK ! I would like to do this. Could you please assign this to me? and if its okay, please add the Hacktoberfest label please. Thanks!

**Comment by devpawann** [comment]
Hey, I am taking this @SankethBK

**Comment by devpawann** [comment]
<table>
    <tr>
        <td><img src="https://github.com/user-attachments/assets/e910af76-5682-4d6b-940d-4131cd6d026c" alt="1" width="200" /></td>
        <td><img src="https://github.com/user-attachments/assets/7ed08067-5146-40f5-99d0-e2c1b1031cd3" alt="2" width="200" /></td>
        <td><img src="https://github.com/user-attachments/assets/e79f803c-c627-4cb8-baa4-926dad81c9a4" alt="3" width="200" /></td>
        <td><img src="https://github.com/user-attachments/assets/21e1e8a3-06b4-4db0-8e2a-9be015957903" alt="4" width="200" /></td>
    </tr>
    <tr>
        <td><img src="https://github.com/user-attachments/assets/aba7958a-1dbd-41c0-8ee0-d0980b7cfe80" alt="5" width="200" /></td>
        <td><img src="https://github.com/user-attachments/assets/a2a3a17c-315c-4f5e-9613-8b87e4742ef4" alt="6 12 44 10 AM" width="200" /></td>
        <td><img src="https://github.com/user-attachments/assets/9ab61528-aa86-409c-9e6f-a76d0ecc131d" alt="8" width="200" /></td>
        <td><img src="https://github.com/user-attachments/assets/086a7805-558d-4fe5-9263-0efc4c15ab22" alt="7" width="200" /></td>
    </tr>
</table>
