### ISSUE TITLE
Show in-app review modal

### ISSUE THREAD

**Issue by SankethBK** [SankethBK/diaryvault#216]
Google Play store supports in-app reviews through which an app can request for review and rating from within the app itself [referece](https://developer.android.com/guide/playcore/in-app-review). We want to show an in-app review once a note is saved. 

Flutter has a package to show the in-app review popup: https://pub.dev/packages/in_app_review. 

Showing the popup is as simple as calling this function

```
  Future<void> showReviewPopup() async {
    if (await inAppReview.isAvailable()) {
      await inAppReview.requestReview();
    }
  }
  ```

This is the code which exits the note page after saving, we can show in-app review modal here before exiting. 
```
 else if (state is NoteSavedSuccesfully) {
                showToast(state.newNote!
                    ? S.current.noteSavedSuccessfully
                    : S.current.noteUpdatedSuccessfully);
                _routeToHome();
              }
```

Relevant widgets
```
- lib/features/notes/presentation/pages/note_create_page.dart
-

**Comment by Prakharpan-dey** [comment]
Hey i am new to open source and i think i can work on this. Could you assign this to me? Also if possible please add hacktober tags .

**Comment by SankethBK** [comment]
Hi @Prakharpan-dey , sure
