### ISSUE TITLE
Declutter Settings Page

### ISSUE THREAD

**Issue by SankethBK** [SankethBK/diaryvault#218]
The current Settings page displays all options on a single screen. Even though similar options are grouped and expandable on click, the page has become cluttered and overwhelming for users.

**Proposed Solution:**

Redesign the Settings page to display only the primary categories:

- **Cloud Backup**
- **Security**
- **Reminders**
- **Customize Theme, Fonts, and Language**

(Keep rest of the options like Send Feedback, Share with Friends, Project on Github and App version as it is)

On clicking these options, further relevant options needs to be displayed on a different screen.

Widgets Involved:
```
- lib/core/pages/settings_page.dart
- lib/core/widgets/settings_tile.dart
```

Tasks

- [ ] Create a new page `settings_details.dart` in ` lib/core/pages`.
- [ ] Remove widgets from `ListView` in `settings_page.dart` and addthe following options. (Use `SettingsTile` widget to display these options.)
    - Cloud Backup 
    - Security
    - Reminders
    - Customize Theme,  Fonts and Language
- [ ] On clicking any of the primary categories, navigate to `settings_details.dart`. Pass route parameters (e.g., **pageTitle**) to identify which category's settings to display in `settings_details.dart`.

**Comment by devpawann** [comment]
@SankethBK assign it to me?

**Comment by SankethBK** [comment]
Sure @devpawann
