### ISSUE TITLE
Redesign Note preview in home page

### ISSUE THREAD

**Issue by SankethBK** [SankethBK/diaryvault#22]
Redesign the `NotePreviewCard` widget.

**Comment by mundadapurva** [comment]
Assign me this one. I would like to work on this.

**Comment by SankethBK** [comment]
Sure

**Comment by SankethBK** [comment]
Hey @mundadapurva , instead of making changes to `NotePreviewCard` itself, create another widget `NotePreviewCard2`. We can let user choose which display format they prefer in settings.

Feel free to join our discord [server](https://discord.com/channels/1153054074875416716/1153054075626213448) if you need help with anything

**Comment by mundadapurva** [comment]
Okay, will do that.
