### ISSUE TITLE
Add Automated Greeting Workflow

### ISSUE THREAD

**Issue by shubhagarwal1** [SankethBK/diaryvault#221]
I propose to create a GitHub workflow named "Greetings". This workflow will automatically greet users who create new issues or pull requests in this repository. The Greeting will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.
Hey @SankethBK  please assign me this task

**Comment by SankethBK** [comment]
Hi @shubhagarwal1 , please go ahead

**Comment by shubhagarwal1** [comment]
pleae assign this task to me @SankethBK

**Comment by shubhagarwal1** [comment]
kindly add all the labels 
gssoc-ext, hacktoberfest, hacktoberfest-accepted, level

**Comment by SankethBK** [comment]
I have added hacktoberfest topic to the repo, all issues will be considered for hacktoberfest!

**Comment by Prakharpan-dey** [comment]
Hey is this being worked on?

**Comment by shubhagarwal1** [comment]
> Hey is this being worked on?

yes almost done

**Comment by Prakharpan-dey** [comment]
@shubhagarwal1 mind closing this?
