### ISSUE TITLE
Display name of the audio file

### ISSUE THREAD

**Issue by SankethBK** [SankethBK/diaryvault#230]
Currently, when an audio file is added to the rich text editor, the editor directly displays an audio player widget. We want to improve the user experience by showing the audio file name before the audio starts playing for the first time. Once the audio starts playing, the audio player widget should appear as usual.

Goal:

- Display the file name of the audio in the initial state (i.e., before the audio starts playing for the first time).
- Once the user starts playing the audio, switch to the audio player widget.
- This behavior should mimic the functionality shown in the attached screenshots.

**Screenshots for Reference:**

Current behaviour

<img width="310" alt="image" src="https://github.com/user-attachments/assets/509f888e-69d9-4653-914d-5e9b871d28db">

Initial state (showing file name):

<img width="250" alt="image" src="https://github.com/user-attachments/assets/f0dd8ea3-e51d-4b27-ba63-17ad2e1aa505">

Relevant widgets
```
- packages/flutter_quill/flutter_quill_extensions/lib/embeds/audio_player.dart
```

**Comment by Prakharpan-dey** [comment]
@SankethBK Hey i wanted to ask if this is what you wanted . If yes assign me this issue i will work on it. Thank you
![Screenshot 2024-10-06 182741](https://github.com/user-attachments/assets/ea4588ae-6e72-4841-8036-d6238d75609f)
![Screenshot 2024-10-06 182751](https://github.com/user-attachments/assets/924baf80-1650-4c76-b7e7-1c5793e55536)

**Comment by SankethBK** [comment]
Hey that's correct, you can keep the duration at the end, also clip the text if its more than 1 line
