### ISSUE TITLE
Implement Auto Labeler GitHub Action for Issues and Pull RequestsLabel 

### ISSUE THREAD

**Issue by shubhagarwal1** [SankethBK/diaryvault#231]
I proposeto  introduces an Auto Labeler GitHub Action that automatically assigns labels to issues and pull requests based on specific keywords found in their titles or bodies. This feature aims to streamline issue tracking and enhance project organization.

**Changes to be  made**
Added a new GitHub Actions workflow that triggers on issue creation and PR opening/editing.
Defined a set of keyword-label mappings to apply the appropriate labels, including:
Bug
Enhancement
Feature
Hacktoberfest
Hacktoberfest-accepted
GSSOC-EXT
Implement logic to check the title and body for these keywords and apply labels accordingly.
Hey @SankethBK please assign this task to me

**Comment by SankethBK** [comment]
Hey @shubhagarwal1 please go ahead!
