### ISSUE TITLE
Support for "daily reminders"

### ISSUE THREAD

**Issue by SankethBK** [SankethBK/diaryvault#24]
Option to send daily reminder notifications in settings at a particular time. User should be edit the reminder time, disable / enable the reminders.

User can enable daily reminders by toggling the switch and select a time (they ahouldn't be allowed to select time if switch isn't on).

[daily_remainder.webm](https://github.com/SankethBK/diaryvault/assets/51091231/6f59cf66-a090-402a-a689-85b1fadbcf11)

We can add two new properties to `UserConfigModel` 
- bool `isDailyReminerEnabled`: to store if daily remainders are enabled
- TimeOfDay `remainderTime`: to store the time at which we should send remainder

`flutter_local_notifications` supports scheduling recurring notifications:

```

  // Schedule the daily notification
  await flutterLocalNotificationsPlugin.zonedSchedule(
    0, // Unique ID for the notification
    'Your Notification Title',
    'Your Notification Body',
    scheduledTime,
    const NotificationDetails(
      android: AndroidNotificationDetails(
        'your_channel_id', // Use the same channel ID as above
        'Your Channel Name',
        'Your Channel Description',
      ),
    ),
    androidAllowWhileIdle: true,
    uiLocalNotificationDateInterpretation:
        UILocalNotificationDateInterpretation.absoluteTime,
    matchDateTimeComponents: DateTimeComponents.time,
  );

```

**Comment by Siddhant097** [comment]
@SankethBK can you assign this issue to me?

**Comment by SankethBK** [comment]
Sure @Siddhant097

**Comment by Siddhant097** [comment]
@SankethBK Can you provide all command to run after cloning on vscode terminal before running the flutter app

**Comment by SankethBK** [comment]
`flutter pub get`
`flutter run`

**Comment by SankethBK** [comment]
@Siddhant097, please confirm if you're working on this, let us know if you're facing any issues

**Comment by Siddhant097** [comment]
@SankethBK yeah i was facing some issues and any changes i was making were not reflection in the app.
today i will start again from start and i will let you know the issue i am facing.

**Comment by SankethBK** [comment]
Sure @Siddhant097 , thanks for updating.

**Comment by Siddhant097** [comment]
@SankethBK once it runs after cloning but after that i run it then this error pops up
Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> Changes are not tracked, unable determine incremental changes.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 6s
Running Gradle task 'assembleDebug'...                            189.3s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by SankethBK** [comment]
@Siddhant097 can you try running in normal mode instead of debug mode
```
flutter pub get
flutter run
```

If you're running with Vscode run button, choose `Run without debugging` option

**Comment by Siddhant097** [comment]
@SankethBK still same error

**Comment by SankethBK** [comment]
Can you share the output of `flutter doctor`

**Comment by Siddhant097** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.6, on Microsoft Windows [Version 10.0.22000.2416], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.2)
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.83.0)
[√] Connected device (4 available)
[!] Network resources
    X A network error occurred while checking "https://pub.dev/": Failed host lookup: 'pub.dev'
    X A network error occurred while checking "https://storage.googleapis.com/": Failed host lookup: 'storage.googleapis.com'        
    X A network error occurred while checking "https://maven.google.com/": Failed host lookup: 'maven.google.com'
    X A network error occurred while checking "https://cocoapods.org/": Failed host lookup: 'cocoapods.org'
    X A network error occurred while checking "https://github.com/": Failed host lookup: 'github.com'

! Doctor found issues in 1 category.

**Comment by Siddhant097** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.6, on Microsoft Windows [Version 10.0.22000.2416], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.2)
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.83.0)
[√] Connected device (4 available)
[√] Network resources

• No issues found!
flutter doctor result now it is fixed but still same error persists

**Comment by Siddhant097** [comment]
yeah 
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> Changes are not tracked, unable determine incremental changes.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 17s
Running Gradle task 'assembleDebug'...                             81.0s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by SankethBK** [comment]
@Siddhant097 can you share the output of `flutter --version`. Also can you create a blank project and try to run it? that will tell us if something is wrong with setup

**Comment by SankethBK** [comment]
Also try running `flutter clean` and then 
```flutter pub get
flutter run```

**Comment by Siddhant097** [comment]
Flutter Version


C:\Users\siddh\OneDrive\Desktop\dairyvault\diaryvault>flutter --version
Flutter 3.13.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ead455963c (13 days ago) • 2023-09-26 18:28:17 -0700
Engine • revision a794cf2681
Tools • Dart 3.1.3 • DevTools 2.25.0

> Also try running `flutter clean` and then
> 
> ```
> flutter pub get
> flutter run
> ```

I already tried this didnt work ok i will try it again

**Comment by SankethBK** [comment]
Can you check this 

> Also can you create a blank project and try to run it? that will tell us if something is wrong with setup

**Comment by Siddhant097** [comment]
> Can you check this
> 
> > Also can you create a blank project and try to run it? that will tell us if something is wrong with setup

checked
working fine
Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...
main.dart:1
Parameter format not correct -
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:59617/hrcYPbseP08=/ws

**Comment by SankethBK** [comment]
I am using flutter 3.13.0, though not sure if it's because of that. Can you join our [discord server]([Discord server](https://discord.gg/S4QkJbV9Vw)), someone with windows setup might be able to help

❯ flutter --version
Flutter 3.13.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision efbf63d9c6 (8 weeks ago) • 2023-08-15 21:05:06 -0500
Engine • revision 1ac611c64e
Tools • Dart 3.1.0 • DevTools 2.25.0

**Comment by SankethBK** [comment]
@Siddhant097 this could the issue https://stackoverflow.com/a/25209204/10553747, can you try moving project to a different folder

**Comment by Siddhant097** [comment]
@SankethBK Not able to setup account 
unknown error occured, please try again is displaying on emulator screen

**Comment by SankethBK** [comment]
@Siddhant097 you can use continue as guest option if sign up doesn't work.

**Comment by SankethBK** [comment]
Sign up should work ideally I'll check why it's not working

**Comment by Siddhant097** [comment]
@SankethBK Sent you pull request

**Comment by SankethBK** [comment]
Thank you @Siddhant097 , iIll review it by today

**Comment by Siddhant097** [comment]
@SankethBK Reviewed it?
