### ISSUE TITLE
Show different voice options for text to speech

### ISSUE THREAD

**Issue by SankethBK** [SankethBK/diaryvault#241]
Currently, DiaryVault provides an option to read out notes using the [flutter_tts](https://pub.dev/packages/flutter_tts) package. At the moment, only the default voice is used for text-to-speech playback. However, the `flutter_tts` package supports multiple voices based on the platform (Android, iOS). We need to provide users with the ability to select from available voices.

**Description**  
- Add a dropdown in the Settings page (`Customize theme, fonts, and language` section) to allow users to select their preferred voice for note reading.
- The dropdown should be similar to the ones already used for theme, font, and language selections.
- List all available voices from `flutter_tts.getVoices()` in the dropdown.
- On selecting a voice, the choice should be saved in Shared Preferences using the `UserConfigCubit`.
- Load the saved voice setting when playing audio next time.

**How to implement**  
- Use `flutter_tts.getVoices()` to retrieve available voices.
- Store the selected voice using `UserConfigCubit.setUserConfig()` and update `UserConfigConstants` with a new constant for storing the active voice.
- Update the audio playback logic in `note_read_button.dart` to use the saved voice from Shared Preferences.

**Checklist**  
- [ ] Add a voice selection dropdown to the Settings page, similar to other customizable options (theme, font, etc.).
- [ ] Fetch and display all available voices from the `flutter_tts` package.
- [ ] Store the selected voice in Shared Preferences using `UserConfigCubit`.
- [ ] Ensure the selected voice is used for future note readings and persists across app restarts.
- [ ] Update relevant widgets and cubit for saving and retrieving the voice setting.

**Relevant Files**  
- `lib/features/notes/presentation/widgets/note_read_button.dart`
- `lib/features/auth/presentation/bloc/user_config/user_config_cubit.dart`
- `lib/features/auth/core/constants.dart`

**Comment by maiHydrogen** [comment]
hi @SankethBK !!
I'm new to this opensource world and first here at the hacktoberfest but i'm quite familiar with the flutter and firebase things can i try to solve this issue for you?

**Comment by SankethBK** [comment]
Hi @maiHydrogen , sure

**Comment by maiHydrogen** [comment]
hey @SankethBK 
![Screenshot 2024-10-17 213656](https://github.com/user-attachments/assets/3e9485b7-ebbb-43ea-9c99-4d4a50cef6f4)
(url)
i'm having various issues while working on this project like when i try to import anyfile it always shows error and somehow i imported it it imported as inused import and so on...

**Comment by maiHydrogen** [comment]
hey @SankethBK 
![Screenshot 2024-10-19 034403](https://github.com/user-attachments/assets/026fff50-d6bb-4e6b-9ce0-f96e4de8a46e)
![Screenshot 2024-10-19 034426](https://github.com/user-attachments/assets/f5d19a18-eb38-41d7-8092-8c363ac2a8eb)
![Screenshot 2024-10-19 034504](https://github.com/user-attachments/assets/768181ce-264d-4b3b-8906-7ebd3d60cd16)
![Screenshot 2024-10-19 034513](https://github.com/user-attachments/assets/f33ddc74-4ea7-461b-81c3-56deed228082)
i have been working on this issue for last couple of days and these are the screenshots of that , but i'm experiencing issues like when i select any voice in dropdown the debug console shows that user config state is changed but when i hit the back button it revert back to the default state which is the first voice on the list and somehow the note read button is not able update voice therefore. I've seen many videos and tutorials online but couldn't find out what's wrong. any suggestions??

**Comment by SankethBK** [comment]
Hi @maiHydrogen , can you raise a PR, i'll take a look at the code once

**Comment by maiHydrogen** [comment]
Ok I'll do that as soon as possible

**Comment by websachinbansal** [comment]
Hello SankethBK, i'm new in this openSourceWorld.As a Flutter developer,  I Would like to Contribute in Flutter Projects. is there any part of this project you want to look after?

**Comment by SankethBK** [comment]
Hi, this issue is already completed, you can check other ones.
