### ISSUE TITLE
Support export to PDF

### ISSUE THREAD

**Issue by SankethBK** [SankethBK/diaryvault#25]
Refer documentation of [notes schema](https://github.com/SankethBK/diaryvault/blob/master/docs.md#3-notes)

We need to generate a PDF with note's `title`, `created_at`, `body` or `plainText`. We can use [pdf](Refer documentation of [notes schema](https://github.com/SankethBK/diaryvault/blob/master/docs.md#3-notes)) package to generate PDF.

Flutter quill also supports converting contents of rich_text editor to HTML. So there it might be possible to show rich text into PDF instead of plainText.

Challenge is to introduce images. We can retrieve all external asset paths of a note from `NoteDependencies` table.

**Comment by mmjsmohit** [comment]
I am interested to work on this issue. Can you please assign this issue to me as a part of Hacktoberfest?

**Comment by SankethBK** [comment]
Sure, feel free to join our discord server https://discord.gg/maxxpRzn if you need any help
