### ISSUE TITLE
Display welcome note

### ISSUE THREAD

**Issue by SankethBK** [SankethBK/diaryvault#27]
Currently when app is opened for first time, the home page is empty. A note which explains all features of app would be nice.

We need to run an `INSERT` query when app is installed in `lib/core/databases/sqflite_setup.dart`

**Comment by okay-pa1** [comment]
I'm a beginner at flutter, I would like to work on this issue could you explain it to me with more details? thank you



> Currently when app is opened for first time, the home page is empty. A note which explains all features of app would be nice.
> 
> We need to run an `INSERT` query when app is installed in `lib/core/databases/sqflite_setup.dart`

**Comment by micedreams** [comment]
@okay-pa1 Maybe I can help with this... 
After the splash screen, the user is redirected to a home screen. 
If the user is entering that screen for the first time... it's very disorienting because of how empty it looks(picture 1). To give the user a better UX... it is important they are given some context.. like an onboarding screen... since this app is trying to be "minimal" and happens to be a notes app... it will be nice to have a welcome note instead... (something prefilled like in picture 2)

<img width="325" alt="Screenshot 2023-09-29 at 19 08 45" src="https://github.com/SankethBK/diaryvault/assets/8918999/b2fd570c-3ea8-48be-a849-41bfac7e9bb7">

<img width="320" alt="Screenshot 2023-09-29 at 19 14 05" src="https://github.com/SankethBK/diaryvault/assets/8918999/4fd1b18f-7016-4f39-bd49-c937eac9523c">

**Comment by okay-pa1** [comment]
@micedreams I understood what should be done but I don't think I can help. I'm sorry. 
Few things I thought are:
>When a new user signs in a welcome note can be created and added to that user's notes in the database.
>When a user uses guest log in the same thing can be done and the welcome note can be cached. 
I hope this helps someone else who wants to take this issue.

**Comment by micedreams** [comment]
@okay-pa1 ok... maybe reading the shared preference and sqflite documentation might help....

**Comment by Illuminati9** [comment]
Hey @micedreams , I would like to work on this issue under **hacktoberfest**. Can you explain me this issue in detail??

**Comment by micedreams** [comment]
@Illuminati9, I think @SankethBK explains it very well in https://github.com/SankethBK/diaryvault/issues/27#issue-1897298597

#### The only thing that's not explicitly mentioned is 

1. When a user opens the app the first time, a value must be stored inside shared preference and checked for every time the user opens the app.
   * If it exists... the app does nothing.
   * If it does not... the app should store that value and then do the insert. 
 
2. One more thing that needs to be taken care of is, once the user gives the sync to the cloud permission. Before syncing the app should check if the note the app automatically created(👆) was edited.
   * If it was edited... the app should sync this note just like a normal note
   * If it was not edited... the app should not sync it. 

(PS I am not sure if the 2nd part should be part of this issue.)

**Comment by SankethBK** [comment]
Hey folks, adding more details related to this. 

@micedreams is right [here](https://github.com/SankethBK/diaryvault/issues/27#issuecomment-1740925240). When user installs the app for first time, home screen will be empty and will not have any notes. So we can show a welcome note and explain the app's features in that note. It would be like any other note, user should be able to delete it.

We can definitely implement it by storing note in shared preferences as @micedreams described [here](https://github.com/SankethBK/diaryvault/issues/27#issuecomment-1741850268). But main challenge with this way is we need to somehow figure out whether this is the first time the user is opening the app or not.

So an easier way would be this: 
All notes are stored in `Notes` Sqflite table. The table is created in this [script](https://github.com/SankethBK/diaryvault/blob/master/lib/core/databases/sqflite_setup.dart). We can be sure that this script runs exactly once when the user installs the app for the first time, so we can run a `INSERT` query here just like we are running other `CREATE TABLE` queries. 

Notes table has following columns

```
Notes {
  final String id;
  final DateTime createdAt;
  final String title;
  final String body;
  final String hash;
  final DateTime lastModified;
  final String plainText;
  final List<NoteAsset> assetDependencies;
  final bool deleted;
  final String? authorId;
}
```

(Its not necessary to know what does each column represent for this issue, you can refer this [part](https://github.com/SankethBK/diaryvault#3-notes) of readme if you want to know)

In order to figure out the values of these columns we can create a welcome note from the app and print these values before it gets inserted to db. `saveNote` function in [`lib/features/notes/data/repositories/notes_repository.dart` ](https://github.com/SankethBK/diaryvault/blob/master/lib/features/notes/data/datasources/local%20data%20sources/local_data_source.dart). Once we have values for all the columns, we can add a hardcoded `INSERT` query in `sqflite_setup.dart` file.

**Comment by SankethBK** [comment]
> One more thing that needs to be taken care of is, once the user gives the sync to the cloud permission. Before syncing the app should check if the note the app automatically created(👆) was edited. 

> If it was edited... the app should sync this note just like a normal note
If it was not edited... the app should not sync it.

@micedreams good point! But there won't be any additional changes required for this. Because in `lib/features/sync/presentation/bloc/notes_sync/notesync_cubit.dart`. Whenver `NoteSavedSuccesfully` or `NoteDeletionSuccesful` events is emitted by `NotesBloc`. We will automatically start syncing to cloud.

**Comment by micedreams** [comment]
> @micedreams good point! But there won't be any additional changes required for this. Because in `lib/features/sync/presentation/bloc/notes_sync/notesync_cubit.dart`. Whenver `NoteSavedSuccesfully` or `NoteDeletionSuccesful` events is emitted by `NotesBloc`. We will automatically start syncing to cloud.

**Comment by micedreams** [comment]
> @micedreams good point! But there won't be any additional changes required for this. Because in `lib/features/sync/presentation/bloc/notes_sync/notesync_cubit.dart`. Whenver `NoteSavedSuccesfully` or `NoteDeletionSuccesful` events is emitted by `NotesBloc`. We will automatically start syncing to cloud.

This makes sense.

**Comment by Illuminati9** [comment]
Hey @SankethBK , Can you specify what are the details should be there in welcome note??

**Comment by SankethBK** [comment]
@Illuminati9 For now you can add key features of the app from readme, we can find tune the content once the functionality is working

**Comment by soam1** [comment]
@SankethBK or can we add something like bundled cardview explaining in one liners what every icon means along with an image representing arrows or whatever. Or we can add something like a carousel slider only for one time.

**Comment by SankethBK** [comment]
Adding Carousel slider when app is opened for first time is a good idea! It might require some effort on creating designs, I will create a separate issue for this.

I still prefer to have welcome note, as it can give a brief idea of how a note would look like without actually creating one

**Comment by droidbg** [comment]
@Illuminati9 @soam1 is any working on it?

**Comment by soam1** [comment]
@droidbg nopes not now.

**Comment by soam1** [comment]
@droidbg nopes not me now

**Comment by PratyushChauhan** [comment]
> @okay-pa1 Maybe I can help with this... After the splash screen, the user is redirected to a home screen. If the user is entering that screen for the first time... it's very disorienting because of how empty it looks(picture 1). To give the user a better UX... it is important they are given some context.. like an onboarding screen... since this app is trying to be "minimal" and happens to be a notes app... it will be nice to have a welcome note instead... (something prefilled like in picture 2)
> 
> <img alt="Screenshot 2023-09-29 at 19 08 45" width="325" src="https://user-images.githubusercontent.com/8918999/271608215-b2fd570c-3ea8-48be-a849-41bfac7e9bb7.png"> <img alt="Screenshot 2023-09-29 at 19 14 05" width="320" src="https://user-images.githubusercontent.com/8918999/271610971-4fd1b18f-7016-4f39-bd49-c937eac9523c.png">

Seems easy enough, please assign it to me.

**Comment by PratyushChauhan** [comment]
Tried to build the app got the following error.
```
*** What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\dev\tooling\flutter\bin\flutter.bat'' finished with non-zero exit value 1**
```

I am referencing this thread -
https://stackoverflow.com/questions/54552962/flutter-build-error-process-command-e-flutter-apps-flutter-bin-flutter-bat

The answer is recommending me to upgrade the dependencies.  Should I do it or is there some other issue?

**Comment by PratyushChauhan** [comment]
Full Error:
```
Launching lib\main.dart on CPH2381 in debug mode...
Running Gradle task 'assembleDebug'...
/C:/Users/ciphe/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_math_fork-0.7.1/lib/src/widgets/selection/gesture_detector_builder_selectable.dart:38:22: Error: Type 'TapDragUpDetails' not found.
  void onSingleTapUp(TapDragUpDetails details) {
                     ^^^^^^^^^^^^^^^^
/C:/Users/ciphe/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_math_fork-0.7.1/lib/src/widgets/selection/gesture_detector_builder_selectable.dart:38:22: Error: 'TapDragUpDetails' isn't a type.
  void onSingleTapUp(TapDragUpDetails details) {
                     ^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception


FAILURE: Build failed with an exception.

* Where:
Script 'C:\dev\tooling\flutter\packages\flutter_tools\gradle\src\main\groovy\flutter.groovy' line: 1297

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\dev\tooling\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6m 23s
Exception: Gradle task assembleDebug failed with exit code 1

```

**Comment by SankethBK** [comment]
@PratyushChauhan can you share the output of `flutter doctor`

**Comment by SankethBK** [comment]
It appears like you have different version of `flutter_math_fork` in cache,`flutter clean` might help

**Comment by PratyushChauhan** [comment]
@SankethBK solved it by switching flutter to ```stable``` channel. Was previously on ```master```.

**Comment by PratyushChauhan** [comment]
![image](https://github.com/SankethBK/diaryvault/assets/109033080/84ecc9cb-8160-4e0b-a0a6-61e4980228ae)

File: lib/features/auth/data/datasources/local data sources/local_data_source.dart

From what I learned digging around the code and logs, this is the place where new users are inserted.
I am thinking of inserting the Welcome note just below the INSERT user query. 
Let me know if this is a good idea or not.

**Comment by SankethBK** [comment]
@PratyushChauhan this function will save the note when it's created by user. But we need to insert the note even before the user opens the app for first time. So it should be in `sqflite_setup.dart` after the create table query. Because this script runs exactly once.  To get the contents for insert query you have to first create a normal note by adding a print statement in saveNote function, refer other comments in this thread for more info

**Comment by PratyushChauhan** [comment]
> Hey folks, adding more details related to this.
> 
> @micedreams is right [here](https://github.com/SankethBK/diaryvault/issues/27#issuecomment-1740925240). When user installs the app for first time, home screen will be empty and will not have any notes. So we can show a welcome note and explain the app's features in that note. It would be like any other note, user should be able to delete it.
> 
> We can definitely implement it by storing note in shared preferences as @micedreams described [here](https://github.com/SankethBK/diaryvault/issues/27#issuecomment-1741850268). But main challenge with this way is we need to somehow figure out whether this is the first time the user is opening the app or not.
> 
> So an easier way would be this: All notes are stored in `Notes` Sqflite table. The table is created in this [script](https://github.com/SankethBK/diaryvault/blob/master/lib/core/databases/sqflite_setup.dart). We can be sure that this script runs exactly once when the user installs the app for the first time, so we can run a `INSERT` query here just like we are running other `CREATE TABLE` queries.
> 
> Notes table has following columns
> 
> ```
> Notes {
>   final String id;
>   final DateTime createdAt;
>   final String title;
>   final String body;
>   final String hash;
>   final DateTime lastModified;
>   final String plainText;
>   final List<NoteAsset> assetDependencies;
>   final bool deleted;
>   final String? authorId;
> }
> ```
> 
> (Its not necessary to know what does each column represent for this issue, you can refer this [part](https://github.com/SankethBK/diaryvault#3-notes) of readme if you want to know)
> 
> In order to figure out the values of these columns we can create a welcome note from the app and print these values before it gets inserted to db. `saveNote` function in [`lib/features/notes/data/repositories/notes_repository.dart` ](https://github.com/SankethBK/diaryvault/blob/master/lib/features/notes/data/datasources/local%20data%20sources/local_data_source.dart). Once we have values for all the columns, we can add a hardcoded `INSERT` query in `sqflite_setup.dart` file.

Taking this as reference.

**Comment by PratyushChauhan** [comment]
I think the authorId in ```Notes``` template will give me trouble while modifying ```sqflite_setup.dart``` .

![image](https://github.com/SankethBK/diaryvault/assets/109033080/23fec99b-7465-4a05-9bcd-7da3231411c9)

LOGS(on a fresh install ```sqflite_setup.dart``` was executed before any user registered):
![image](https://github.com/SankethBK/diaryvault/assets/109033080/a54bdb5d-6254-49db-b752-20672e6373f5)

I added an insert query but the notes were not visible.
According to the logs, this table is initialized BEFORE any users are registered, therefore notes inserted in ```sqflite_setup.dart``` will 
 not be visible to our user since we did not know his authorId. 
 
Is there an authorId whose notes are visible to all users? 
We could either do that OR insert a note (whenever a new user is created) in ```authentication_repository.dart``` .

**Comment by SankethBK** [comment]
Set authorId to `guest_author_id`, it should be visible

**Comment by PratyushChauhan** [comment]
Been stuck on this for a while.
```
await db.execute("""
            INSERT INTO ${Notes.TABLE_NAME} (
              ${Notes.ID},
              ${Notes.CREATED_AT},
              ${Notes.TITLE},
              ${Notes.BODY},
              ${Notes.HASH},
              ${Notes.LAST_MODIFIED},
              ${Notes.PLAIN_TEXT},
              ${Notes.DELETED},
              ${Notes.AUTHOR_ID}
            ) VALUES (
              "",
              "",
              "Welcome to Dairy App",
              "This is a welcome note. You can delete this note and start writing your own notes.",
              "welcome_note_hash",
              "",
              "This is a welcome note. You can delete this note and start writing your own notes.",
              0,
              "guest_user_id"
            )
            """);
```
ERROR: 
![image](https://github.com/SankethBK/diaryvault/assets/109033080/aedd3a01-b394-4e2f-ab11-81369c9ed2ba)

**Comment by SankethBK** [comment]
@PratyushChauhan can you raise a PR, i'll check the error by running locally

**Comment by PratyushChauhan** [comment]
will do

**Comment by PratyushChauhan** [comment]
which branch should i open a pr for?

**Comment by SankethBK** [comment]
master

**Comment by PratyushChauhan** [comment]
done

**Comment by SankethBK** [comment]
@PratyushChauhan this query is working

```

          log.i("Inserting welcome note");
          await db.execute("""
            INSERT INTO ${Notes.TABLE_NAME} (
              ${Notes.ID},
              ${Notes.CREATED_AT},
              ${Notes.TITLE},
              ${Notes.BODY},
              ${Notes.HASH},
              ${Notes.LAST_MODIFIED},
              ${Notes.PLAIN_TEXT},
              ${Notes.DELETED},
              ${Notes.AUTHOR_ID}
            ) VALUES (
              "f773a170-6447-11ee-9a76-c314b6be99a3",
              1696597075215,
              "Welcome to DiaryVault",
              '[{\"insert\":\"This\",\"attributes\":{\"bold\":true}},{\"insert\":\"is\",\"attributes\":{\"bold\":true,\"italic\":true}},{\"insert\":\"welcome\"},{\"insert\":\"note\",\"attributes\":{\"color\":\"#FF03A9F4\"}},{\"insert\":\"\\n\"}]',
              "welcome_note_hash",
              1696597122553,
              "This is a welcome note. You can delete this note and start writing your own notes.",
              0,
              "guest_user_id"
            )
            """);
```

I got the content of body by printing `$noteMap` in `saveNote` function
<img width="688" alt="image" src="https://github.com/SankethBK/diaryvault/assets/51091231/43b99710-7a3e-443c-b8eb-8e31521ce59b">

**Comment by PratyushChauhan** [comment]
Any particular reason why it failed to fetch the previous query?

**Comment by PratyushChauhan** [comment]
Will update branch and push.

**Comment by SankethBK** [comment]
Rich text editor expects `body` to be in delta format, but in your case its text. Also `created_at` cannot be empty.

**Comment by PratyushChauhan** [comment]
Got it thanks

**Comment by PratyushChauhan** [comment]
![image](https://github.com/SankethBK/diaryvault/assets/109033080/21362d0f-74ae-440e-a5ca-7cfcb4ce783a)

Changed the welcome message a little
