### ISSUE TITLE
Auto save notes for every "x" seconds

### ISSUE THREAD

**Issue by SankethBK** [SankethBK/diaryvault#29]
Refer to the documentation of [notes schema](https://github.com/SankethBK/diaryvault/blob/master/docs.md#3-notes)

Notes bloc is defined in `lib/features/notes/presentation/bloc/notes`. We need to emit the `SaveNote` event with a timer of "x" seconds. 

Use `Timer.periodic` to emit this event in `lib/features/notes/presentation/pages/note_create_page.dart`. 

Next step would be to make "x" configurable by taking an input from settings

**Comment by droidbg** [comment]
@SankethBK Picking this up.
