### ISSUE TITLE
Support for organizing notes in the form of hierarchy of folders

### ISSUE THREAD

**Issue by SankethBK** [SankethBK/diaryvault#30]
Needs more research, we can collaborate on this if you're interested!

**Comment by Naveenchand06** [comment]
@SankethBK I would like to work on this issue, can we collaborate?

**Comment by SankethBK** [comment]
Thanks @Naveenchand06 , i will come up with more details by the end of this week

**Comment by Naveenchand06** [comment]
> Thanks @Naveenchand06 , i will come up with more details by the end of this week

Okay : )
