### ISSUE TITLE
Refactor settings page

### ISSUE THREAD

**Issue by SankethBK** [SankethBK/diaryvault#39]
Settings page is getting cluttered with lot of options. 

<img src="https://github.com/SankethBK/diaryvault/assets/51091231/0fddaad6-648d-4c8c-9579-c0854272cbe7" width = "400" />

Instead of displaying all options linearly, we can group bunch of related options into an [accordion](https://blog.hubspot.com/hs-fs/hubfs/accordion-design_4.webp?width=800&height=1022&name=accordion-design_4.webp).

For now we can group these options `Change password`, `Change Email` and `Enable Fingerprint login` into `Security Settings`

Initially Security settings will be shown

<img src="https://github.com/SankethBK/diaryvault/assets/51091231/90a3e189-619d-4650-a898-cab8df07fb3e" width = "400" />

On clicking it will expand to show all 3 options 

<img src="https://github.com/SankethBK/diaryvault/assets/51091231/5b6db4e7-f3a1-47ff-bc4f-947b63107632" width = "400" />
 
Screenshots are just for reference. Feel free to use [accordion](https://pub.dev/packages/accordion/example) package or implement your own widget

**Comment by sameer1612** [comment]
I can take it, do assign if up for grabs. Thanks!

**Comment by SankethBK** [comment]
Sure, assigning it to you. Feel free to join our discord [server](https://discord.gg/qgbnnSGz) if you need help with anything

**Comment by sameer1612** [comment]
@SankethBK seems blocked here.  Flutter's native expansion panel is broken. Doesn't even work on the official website. https://api.flutter.dev/flutter/material/ExpansionPanelList-class.html

Another option we had was to use Accordion library which has a bug with transparent background. I raised an issue but can't expect a resolution soon. https://github.com/GotJimmy/accordion/issues/55

Only option we have in hand is to use a deep blue color instead of waiting for transparent background support. What you suggest?

**Comment by SankethBK** [comment]
@sameer1612 how about creating our own accordion widget?

Not sure if `AnimatedCrossFade` would work here. If not we may have to use `AnimatedSize` or something. Let me know if this helps

```
import 'package:flutter/material.dart';

class CustomAccordion extends StatefulWidget {
  final Widget header;
  final List<Widget> children;

  CustomAccordion({required this.header, required this.children});

  @override
  _SmoothAccordionState createState() => _SmoothAccordionState();
}

class _CustomAccordionState extends State<Accordion> {
  bool _isExpanded = false;

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        ListTile(
          title: widget.header,
          onTap: () {
            setState(() {
              _isExpanded = !_isExpanded;
            });
          },
          trailing: _isExpanded ? Icon(Icons.expand_less) : Icon(Icons.expand_more),
        ),
        AnimatedCrossFade(
          firstChild: Container(),
          secondChild: Column(
            children: widget.children,
          ),
          crossFadeState: _isExpanded ? CrossFadeState.showSecond : CrossFadeState.showFirst,
          duration: Duration(milliseconds: 300), // Adjust the duration as needed
        ),
        Divider(height: 1), // Add a divider to separate accordions
      ],
    );
  }
}```

We can use it as 

```
CustomAccordion(header: Text("Security Settings", children: [
    Text("change password), ...
])

**Comment by sameer1612** [comment]
Luckily landed up with a library that doesn't mess up with glassmorphic design. Looks good!

![ezgif com-video-to-gif](https://github.com/SankethBK/diaryvault/assets/39580073/574eb500-de29-4286-9abc-7d65f483b297)


Here's a PR: [https://github.com/SankethBK/diaryvault/pull/48](https://github.com/SankethBK/diaryvault/pull/48)
