### ISSUE TITLE
Testcases Failing

### ISSUE THREAD

**Issue by droidbg** [SankethBK/diaryvault#46]
## Describe the Issue
Testcases in test folders are failing due to different schemas changes. 

## To Reproduce
1. Clone Repo.
2. Inside Test folder, we can see many test files are red. 

## Expected behavior
Testcases should have proper schemas. 

## Screenshots/Video

<img width="1648" alt="Screenshot 2023-10-02 at 1 51 17 PM" src="https://github.com/SankethBK/diaryvault/assets/41873024/d90d8401-eab3-4126-877b-abbb36bcd2d9">

**Comment by droidbg** [comment]
@SankethBK I Like to pick this up, can you assign hacktoberfest label to it.

**Comment by SankethBK** [comment]
@droidbg sure

**Comment by droidbg** [comment]
This is fixed, will raise the PR in some time.
