### ISSUE TITLE
[Feature]: Make it available for windows, Macos and Linux app as well

### ISSUE THREAD

**Issue by AliYar-Khan** [SankethBK/diaryvault#51]
Since Flutter is cross platform and single code runs on all platform, we can make the other versions as well.
Not all people like to keep diary in the mobile as it is difficult to write using mobile keyboards. Making the desktop version available will help them writing the diaries easily on their desktops as well

**Comment by SankethBK** [comment]
Hi @AliYar-Khan , yes it will definitely increase the overall usability of the app. I will come up with a roadmap to migrate each screen to desktop version.

**Comment by AliYar-Khan** [comment]
Looking forward to it

**Comment by AnAverageBeing** [comment]
yes me to i am using minidiary.app (open source diary app for desktop) rn and i want to sometime read or write diary on go and i want something cross platform with sync as i am not so good with fronted i was looking for something like this i am looking forward to it and i am also learning flutter so may be i can help in future too

**Comment by SankethBK** [comment]
@AnAverageBeing yes definitely, once we have a stable set of features for the mobile version (I am hoping by the end of October). We can plan for migrating it to different Desktop versions
