### ISSUE TITLE
Fix calendar theme

### ISSUE THREAD

**Issue by SankethBK** [SankethBK/diaryvault#53]
Calendar appears in white color, even if we select dark mode themes. Need to check which attribute of ThemeData is used by `datetime_picker` for displaying the color here and set it to dark color accordingly

Note: The datetime_picker is displayed from within `flutter_quill` library. But it is reading one of the colors from ThemeData which is somehow white in all 3 themes.

<img src="https://github.com/SankethBK/diaryvault/assets/51091231/8b164aa2-4565-45b0-93db-3ec6b8c3556d" width = "500" />

**Comment by djv03** [comment]
hey @SankethBK can I start working on this issue?

**Comment by SankethBK** [comment]
Hi @ayato91 , assigning this to you. We don't have any bots configured yet

**Comment by ARP1208** [comment]
Please assign me this

**Comment by SankethBK** [comment]
@ayato91 can you please confirm if you're working on this

**Comment by SankethBK** [comment]
@ARP1208 we have some more open issues, see if you can pick any. You can raise new issues if you find any bug, or have ideas for enhancement or new features
