### ISSUE TITLE
Add subtitle for "Enable Auto Sync" SwitchListTile

### ISSUE THREAD

**Issue by SankethBK** [SankethBK/diaryvault#59]
Add subtitle for "Enable Auto Sync" SwitchListTile. Subtitle: `Automatically saves your notes after every "10" seconds`

<img src="https://user-images.githubusercontent.com/41873024/271915890-bbcbd915-1ad7-4d43-9bc7-695c17e39978.png" width = "500" />

**Comment by MaryamMansour** [comment]
Hi, is this issue still open? can i work on it for hacktoberfest?
 also is it just adding subtitle or there's more to do

**Comment by SankethBK** [comment]
@MaryamMansour yes it's still open, we only need to add subtitle

**Comment by MaryamMansour** [comment]
@SankethBK alright, I'll be working on it
