### ISSUE TITLE
Implement Text-to-Speech Feature for Note Content Reading

### ISSUE THREAD

**Issue by SankethBK** [SankethBK/diaryvault#60]
In the NotesReadOnlyPage, we can introduce a "Play" button that, when clicked, will read aloud the contents of the note, including both the title and the body.

To accomplish this, we can leverage the [flutter_tts](https://pub.dev/packages/flutter_tts) library, which provides text-to-speech capabilities for Flutter applications.

Additionally, as part of this enhancement, we can explore the possibility of enabling background playback for the audio. This means that users can continue to listen to their notes being read even when the app is not in focus or running in the background.

For now we can use hardcoded voice type, we can make voice, pitch and other things configurable in future.

<img src="https://github.com/SankethBK/diaryvault/assets/51091231/130e9b11-d299-4f41-89b5-3bb9b7859a06" /> 

Body of the note will be in delta form, it can be converted to plainText by `state.controller!.document.toPlainText()`.

**Comment by vaibhavppandey** [comment]
hey @SankethBK, I would love to try this. Could you please assign this issue to me?

**Comment by SankethBK** [comment]
Sure @vaibhavppandey @Night-Amber3301 has contributed some code related to this, it needs some refactoring. You can use this branch as starting point https://github.com/SankethBK/diaryvault/tree/feat/read_notes
