### ISSUE TITLE
Need help with fixing syntax errors!!

### ISSUE THREAD

**Issue by micedreams** [SankethBK/diaryvault#67]
Need help with fixing these syntax errors like these...
 
<img width="1383" alt="Screenshot 2023-10-07 at 05 49 52" src="https://user-images.githubusercontent.com/8918999/273351749-debb3f89-0e54-4c27-b83c-d4912aabf6bc.png">

Steps to recreate:
1.  make sure to have [this](https://github.com/SankethBK/diaryvault/pull/66/files#diff-a58d5995c53d2528e852d3b32cfd236c6c0e8498880065242df4e879273de061) file in your root directory
2. In your terminal run: ` bash pre-commit`

_Originally posted by @micedreams in https://github.com/SankethBK/diaryvault/issues/66#issuecomment-1751521221_

**Comment by bibekpanda55** [comment]
Can work on it. Please assign it to me

**Comment by SankethBK** [comment]
Sure @bibekpanda55

**Comment by SankethBK** [comment]
This is done!
