### ISSUE TITLE
Add scroll padding

### ISSUE THREAD

**Issue by SankethBK** [SankethBK/diaryvault#68]
Some websites have extra padding at the end of the page, so that users don't have to change their eye level while reading the content at the end of the page (even VSCode allows has an option to allow scroll beyond the last line).

This design element is used to enhance the user experience by ensuring that the last lines of text or content are not too close to the bottom of the viewport, making it more comfortable for users to read.

Currently when writing a note as we hit the last line we are forced to change the eye level to the bottom of the screen as we cannot scroll beyond the last line, or we have to insert blank lines every time we hit the bottom of the page just for scrolling.

Refer to this screen recording for demo.

[scroll_padding.webm](https://vimeo.com/user121881110/).

Text editor is in this widget `RichTextEditor` (`lib/features/notes/presentation/widgets/rich_text_editor.dart`)

I am thinking adding a `SizedBox(height: 200)` to `GlassPaneForEditor` widget and wrapping it with `SingleChildScrollView` might solve the issue.

**Comment by apikmeister** [comment]
Hi, I would like to work on this, can you assign me? Thank you!
