### ISSUE TITLE
Download options

### ISSUE THREAD

**Issue by IzzySoft** [SankethBK/diaryvault#70]
First thanks for providing your app the FOSS way: open source, and without any trackers! Would you also consider making it available outside of Google's walled garden, for those who have no access to PlayStore? Like, attaching the APKs to their corresponding [releases](https://github.com/SankethBK/diaryvault/releases) – or even bring the app to [F-Droid](https://f-droid.org/)?

**Comment by SankethBK** [comment]
Yes, it's automatically mirrored into some APK stores. I wanted upload to F-Droid, but it violates one of one of their policies since we're using Firebase SDK. I tried attaching APK files to GitHub releases, but unfortunately it doesn't let us attach apk files.

**Comment by IzzySoft** [comment]
Thanks for your reply! Well, depending on what you use Firebase for, most of it is covered by its FOSS alternatives [Supabase](https://supabase.com/) and [appwrite](https://github.com/appwrite/appwrite), so you might wish to look into replacing it with one of those.

As for attaching APK files: that should work perfectly fine, most Android FOSS projects have their APKs there. It might not work attaching them inside an issue like here, but at releases (where I've linked to) it does work. There are even Github actions available to automate that. Could you please check again to make sure? I could show you thousands of projects (and I do not exaggerate here) providing their APKs that way.

**Comment by SankethBK** [comment]
We are using Firebase for Authentication, which can be replaced by Supabase or Appwrite as you mentioned. But we are also using `google_sign_in` which is required for sending requests to google drive, need to check if its allowed by F-Droid policy. 

I was able to attach APK as binary: https://github.com/SankethBK/diaryvault/releases/tag/2.1.1

**Comment by IzzySoft** [comment]
Google SignIn, when accomplished without any proprietary libraries, would just mean the app getting the `NonFreeNet` (and maybe `Tracking`) anti-feature applied, GDrive would need the former as well. I'd not trust any personal details (especially not my diary) to an app with Google ties, and quite a few in the FOSS community feel the same – but that's a choice every person has to make for themselves of course.

Thanks for attaching the APK! I've just run it through one of the scanners also used by F-Droid, and it mentions the following "problem candidates":

```
Offending libs:
---------------
* Google Mobile Services (/com/google/android/gms): NonFreeComp
* Google Play Core (/com/google/android/play/core): NonFreeNet,NonFreeComp
* Firebase (/com/google/firebase): NonFreeNet,NonFreeComp
* FlutterFire (/io/flutter/plugins/firebase): NonFreeNet

4 offenders.
```

Libraries marked `NonFreeComp` (non-free component) are show-stoppers for F-Droid – which is all of the four but FlutterFire (though FlutterFire would drag in at least Firebase again).

Maybe you'd consider a `foss` build variant that doesn't need any of the four, and thus could work without Google ties? Then you could still ship the "full setup" including GDrive and GSignIn to Playstore, while the FOSS variant (maybe without Drive support, maybe with Nextcloud instead – whichever you choose) could become available at F-Droid.

**Comment by SankethBK** [comment]
Sure, it should be possible, we already have Dropbox as another sync source. If we manage to migrate authentication, then we just need to disable G-Drive for `foss` builds. I'll update on this.

**Comment by IzzySoft** [comment]
Thanks! If there's a build with those ties cut, could you please also provide per-ABI builds (to get the APK size down)? I would then offer to provide it via [my repo](https://apt.izzysoft.de/fdroid) until it was integrated with F-Droid.org itself.

**Comment by SankethBK** [comment]
Sure, I'll make sure to attach per-abi builds once we are done with migration. Thank you.

**Comment by SankethBK** [comment]
@IzzySoft we have migrated authentication to Appwrite, and removed google services. I have attached per abi builds [here](https://github.com/SankethBK/diaryvault/releases/tag/2.1.1). Can you please check if it meets the foss compilance

**Comment by IzzySoft** [comment]
That looks excellent, thanks!

```
Libraries detected:
-------------------
* Android PackageManager (/android/content/pm): Utility, Apache-2.0
* Android Support v4 (/android/support/v4): Development Framework, Apache-2.0
* AndroidX Activity (/androidx/activity): Utility, Apache-2.0
* Android Jetpack Annotations (/androidx/annotation): Utility, Apache-2.0
* AppCompat (/androidx/appcompat): Utility, Apache-2.0
* Biometric (/androidx/biometric): Utility, Apache-2.0
* Browser (/androidx/browser): Utility, Apache-2.0
* Concurrent (/androidx/concurrent): Utility, Apache-2.0
* Androidx Core (/androidx/core): Utility, Apache-2.0
* Android Emoji2 Compat (/androidx/emoji2): UI Component, Apache-2.0
* Exifinterface (/androidx/exifinterface): Utility, Apache-2.0
* AndroidX Fragment (/androidx/fragment): UI Component, Apache-2.0
* Lifecycle (/androidx/lifecycle): Utility, Apache-2.0
* Loader (/androidx/loader): Utility, Apache-2.0
* AndroidX Media (/androidx/media): Utility, Apache-2.0
* ProfileInstaller (/androidx/profileinstaller): Utility, Apache-2.0
* Android Activity Saved State (/androidx/savedstate): Utility, Apache-2.0
* AndroidX Security (/androidx/security): Utility, Apache-2.0
* Startup (/androidx/startup): Utility, Apache-2.0
* Swiperefreshlayout (/androidx/swiperefreshlayout): UI Component, Apache-2.0
* Vectordrawable (/androidx/vectordrawable): UI Component, Apache-2.0
* Android Jetpack VersionedParcelable (/androidx/versionedparcelable): Utility, Apache-2.0
* Jetpack WindowManager Library (/androidx/window): Utility, Apache-2.0
* ExoPlayer (/com/google/android/exoplayer2): Utility, Apache-2.0
* Tink (/com/google/crypto/tink): Utility, Apache-2.0
* File Picker (/com/mr/flutter/plugin/filepicker): UI Component, MIT
* Flutter InAppWebView Plugin (/com/pichillilorenzo/flutter_inappwebview): Utility, Apache-2.0
* OkHttp (/com/squareup/okhttp): Utility, Apache-2.0
* share_plus (/dev/fluttercommunity/plus/share): Utility, BSD-3-Clause
* Flutter (/io/flutter): Development Framework, BSD-3-Clause
* Image Picker plugin for Flutter (/io/flutter/plugins/imagepicker): Utility, BSD-3-Clause
* local_auth (/io/flutter/plugins/localauth): Utility, BSD-3-Clause
* url_launcher (/io/flutter/plugins/urllauncher): Utility, BSD-3-Clause
* Kotlin (/kotlin): Utility, Apache-2.0
* kotlinx.coroutines (/kotlinx/coroutines): Utility, Apache-2.0
* Webkit Boundary Interfaces (/org/chromium/support_lib_boundary): Utility, BSD-3-Clause

No offending libs found.
```

(first app in my repo using AppWrite, so that library was not yet detected – will add it when integrating your app). Picking the arm64 variant for my repo now if that's fine with you – once F-Droid picks it up, the other ABIs will become available there then (that's supported with F-Droid.org, but not with my repo).

**Comment by SankethBK** [comment]
> Picking the arm64 variant for my repo now if that's fine with you

Yes, absolutely. Just one question, when you publish it in your repo, will it be automatically picked up by F-Droid or do we need to deploy it separately to F-Droid?

**Comment by IzzySoft** [comment]
OK, is set up … compiling the index now for verification … done: should [show up here](https://apt.izzysoft.de/packages/me.sankethbk.dairyapp/) with the next sync around 6 pm UTC. I wonder that AppWrite libraries are not found by my scanner (and not reported as "unknown" either); maybe some Proguard thingy?

Btw: I've added the `NonFreeNet` anti-feature with a proper explanation (bound to the libre AppWrite.io) for now. This is only temporary until the new `TetheredNet` is established at F-Droid.org (I cannot be sure it will be named exactly like that, hence I better wait to not have collisions later). The explanation should make it pretty clear this is not an issue but simply means "you are not free to choose your own server on the net".

So once the app shows up, be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) and lin there e.g. from your Readme!

And yes, you'll need to submit it to FDroid separately; see e.g. [Quick path to get your app into F-Droid](https://gitlab.com/-/snippets/1896503#quick-path-to-get-your-app-into-f-droid) for some orientation. F-Droid will want you to establish fastlane structures here; see my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) for guidance with that task. If you want, I can also open a PR sending you what I've established at my end, so you have a "starter package" for this.

**Comment by SankethBK** [comment]
Thank you for publishing! just a small correction we use Appwrite only authentication and Dropbox as cloud backup for storing notes (data will be stored in user's own Dropbox account) which i guess still falls under `NonFreeNet`.  Just wanted to confirm if we provided a way to use user's own file-server for storing backups will it still be considered as `NonFreeNet`? (Because authentication info would still be on Appwrite server, but they'll be store notes on their server)

> So once the app shows up, be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) and lin there e.g. from your Readme!

Thanks for the badge, added it.

Also what is the process for publishing update to [IzzySoft](https://apt.izzysoft.de/fdroid/index/apk/me.sankethbk.dairyapp/) store?

>  If you want, I can also open a PR sending you what I've established at my end, so you have a "starter package" for this.


Yes that will be super helpful. I am still new to open source ecosystem, trying to understand how deployments work in F-Droid.

**Comment by IzzySoft** [comment]
> Thank you for publishing! just a small correction we use Appwrite only authentication and Dropbox as cloud backup for storing notes

Thanks for the details! So I made that "The app is bound for authentication to AppWrite.io which is libre, but you cannot change the server, and uses Dropbox for storage." That OK? And yes, Dropbox is definitely `NonFreeNet`.

> Just wanted to confirm if we provided a way to use user's own file-server for storing backups will it still be considered as `NonFreeNet`?

No, of course not: they are then free to choose. Take e.g. WebDAV, and they could use their (self-hosted) NextCloud even.

> Because authentication info would still be on Appwrite server

Yes. But that part would be re-labeled to `TetheredNet` once that's available – which clearly indicates the service is libre, but you just cannot select the server yourself. `NonFreeNet` is already a "minor" one, so `TetheredNet` for most people will be something to ignore (except for those who can self-host etc).

> Thanks for the badge, added it.

Yay, thanks! :star_struck: When does it become visible? I still only see the PlayStore one.

> Also what is the process for publishing update to [IzzySoft](https://apt.izzysoft.de/fdroid/index/apk/me.sankethbk.dairyapp/) store?

Create a tag, then a release, make sure it's properly named (following the same patterns as the last one), and attach the APK (again, using the same naming pattern) – so nothing you'd not do anyway. My updater should then pick up the APK within 24h:

```yaml
    Method: github-release
    GHSkipPre: 1
    ApkMatch: /arm64-v8a/i

AllowedAPKSigningKeys: 5420dc09663961b364f821532ca114544ff6f959d6ba80e605cc6de7f3ab7bb0

AutoUpdateMode: Version %v
UpdateCheckMode: Tags
```

If you want my updater skip a release, simply mark it pre-release :wink: And take good care for your signing key (see: [How to keep your key safe and what measures to take for the event of loss?](https://f-droid.org/2023/09/03/reproducible-builds-signing-keys-and-binary-repos.html#lessons-learned-2-how-to-keep-your-key-safe-and-what-measures-to-take-for-the-event-of-loss)).

> "starter package"

OK, will prepare it then.

**Comment by IzzySoft** [comment]
And there you go :smiley:

**Comment by SankethBK** [comment]
> No, of course not: they are then free to choose. Take e.g. WebDAV, and they could use their (self-hosted) NextCloud even.

Thank you we'll plan to add NextCloud integration.

> Yay, thanks! 🤩 When does it become visible? I still only see the PlayStore one.

Merged the PR, it's visible now

> Create a tag, then a release, make sure it's properly named

I have previously named foss builds with `foss_build_` prefix as one of the APK's was from Google play, should i follow the same naming convention for apk's?

> And take good care for your signing key (see: [How to keep your key safe and what measures to take for the event of loss?](https://f-droid.org/2023/09/03/reproducible-builds-signing-keys-and-binary-repos.html#lessons-learned-2-how-to-keep-your-key-safe-and-what-measures-to-take-for-the-event-of-loss)).

Yes I have stored backups in cloud

> And there you go 😃

Thanks a lot! I will start setting up Fastlane

**Comment by IzzySoft** [comment]
BTW: Please remember increasing `versionCode` with each release. Seems like the current release has the same `versionCode` as the previous one, my updater complained:

    Binary files /web/ftp/repo/fdroid/repo/me.sankethbk.dairyapp_2007.apk and /web/ftp/repo/fdroid/repo/me.sankethbk.dairyapp_2.1.3.apk differ

Which means release 2.1.3 was pulled, the APK was different – but had the same `versionCode` as the existing APK. So nobody will receive any update notification, as Android thinks "I have this already".

**Comment by SankethBK** [comment]
Oh ok, Afaik I previously used `versionCode` 8 for some releases but didn't commit it to github, now I am using `versionCode` 9. I might have used 9 previously, I will try to create another release with `versionCode` 10 

https://github.com/SankethBK/diaryvault/pull/112/files

**Comment by SankethBK** [comment]
Is it possible to find out what is the previous `versionCode` used?

**Comment by SankethBK** [comment]
My bad, I updated the `versionCode` in Github, but while creating the APK my local branch didn't have that changes so its built with previous `versionCode` i.e., 7. 

I have updated the new APKs in release with updated `versionCode`

**Comment by IzzySoft** [comment]
As the current release was already pulled (and thus won't be pulled again by my updater): shall I replace the APK manually, or shall we simply wait for the next release to "clear things up"?

**Comment by SankethBK** [comment]
I'll create another release by tomorrow

**Comment by IzzySoft** [comment]
Then lets wait for that. Replacing a release might cause confusion – a new release is a clean approach. Thanks!

**Comment by SankethBK** [comment]
Hi I've created a new [release](https://github.com/SankethBK/diaryvault/releases/tag/2.1.4) with updated `versionCode` I assume it would be reflected at 6pm UTC on your repo right?

**Comment by IzzySoft** [comment]
Sorry, missed the notification… Yes, that's around the time the index is pushed and processed.

**Comment by SankethBK** [comment]
Hi @IzzySoft , I want to update the description and screenshots in your repo. I wanted to check if it will be automatically updated if I change it in fastlane files, or should I raise a PR to your repo?

**Comment by IzzySoft** [comment]
The following will be checked and updated automatically when a new release is pulled:

```yaml
    Fastlane: https://github.com/SankethBK/diaryvault/tree/master/fastlane/metadata/android
    FastlaneFeatures: shortdesc,fulldesc,icon,featureGraphic,screenshots
```

So unless you added new "elements" (e.g. title.txt or video.txt), updates will happen automatically.

**Comment by SankethBK** [comment]
Thanks for confirming!

**Comment by SankethBK** [comment]
Hi @IzzySoft , I have replaced the images at https://github.com/SankethBK/diaryvault/tree/master/fastlane/metadata/android/en-US/images/phoneScreenshots in the latest release. But instead of replacing old images its showing both old and new images at https://apt.izzysoft.de/fdroid/index/apk/me.sankethbk.dairyapp/. Can you check if I missed anything?

**Comment by SankethBK** [comment]
I guess previous images had .jog extension and current images have .png extension, so probably new files didn't overwrite old files. 
<img width="493" alt="image" src="https://github.com/SankethBK/diaryvault/assets/51091231/2e689aef-c851-42f7-a3c6-0f3801b20a48">

**Comment by IzzySoft** [comment]
You changed the file type, but not the "basename". The check for "obsolete screenshots" just goes by the name without the extension. I've manually removed the JPEGs now, so with the next sync this should be fixed.

**Comment by SankethBK** [comment]
Thank you! So next time if I want to change any image, I should only rename that image right?

**Comment by IzzySoft** [comment]
Not exactly. Say you want to replace `01.png`. So you simply modify that file and check it in. As there already is a `01.png`, the file will be replaced here by my updater as it is newer than the one already present. The only case where it gets tricky is would you replace `01.png` by `01.jpg` (i.e. change the extention), as we just had. All other cases should be handled fine. Should you e.g. remove `01.png`, it would be removed here as well unless some other `01.*` were present.

**Comment by SankethBK** [comment]
Got it, thank you!

**Comment by IzzySoft** [comment]
Side-note: Updates for your app in my repo are currently stalled until we can find a way out, so here the app is still using the previous signature.

**Comment by SankethBK** [comment]
Hi @IzzySoft , I created a new [release 2.2.1
](https://github.com/SankethBK/diaryvault/releases/tag/2.2.1) 2 days ago, i think the duplicate images issue is resolved, but I am not able to see updated version at
https://apt.izzysoft.de/fdroid/index/apk/me.sankethbk.dairyapp/ Can you please check if there was any error during pulling the new build.

**Comment by SankethBK** [comment]
Sorry, my bad. I accidentally changed the package name for some debugging and merged it. I'll revert to previous package name and create another release.

**Comment by IzzySoft** [comment]
And that solved it, even though I was not present for manual actions :smile:

**Comment by IzzySoft** [comment]
PS: we've discussed Fastlane above (thanks for setting it up!) – can you please make sure to stay within the limits of its specifications? Currently, your short description for en-US has 83 chars and thus will be cut off mid-word at character 80 (the size limit for short descriptions). Thanks!

**Comment by SankethBK** [comment]
Sure I'll update it
