### ISSUE TITLE
Implement PIN based authentication - 1

### ISSUE THREAD

**Issue by SankethBK** [SankethBK/diaryvault#71]
Currently, we support email+password and fingerprint login. PIN-based authentication will help in devices that don't support fingerprint login, as typing email+password every time would be tedious. 

I have broken down this into two issues since this is a relatively big feature. 

### 1. Add "Enable PIN-based login" `SwitchListTile` in security settings

<img src="https://github.com/SankethBK/diaryvault/assets/51091231/2a5beca0-50ab-4c8a-8254-ef285586ca8f" width="500" />

We store all user-based settings in `UserConfigModel`, add a new field `isPINLoginEnabled` to store the value of `SwtichListTile`

When user enables this switch we need to check if `userId` (present in `UserConfigCubit`) is not equal to `guest_user_id`. Becuase if guest users forget their PIN, there is no way to recover the data (Same check is also added to "Enable Fingeprint Login" `SwitchListTile`).

### 2. Display a popup like this to collect 4-digit PIN

<img src="https://github.com/SankethBK/diaryvault/assets/51091231/d8f027cf-a4bc-420b-8c26-3123cba559d9" width="500" />

Keyboard should only display numbers, add validation to check if both PINs are matching, otherwise display error in a error message. Refer `passwordResetPopup`, most parts of this widget can be re-used. 

### 3, Saving the PIN

Create a new repository `PINAuthRepository` in `lib/features/auth/data/repositories` and implement `savePIN` in `PINAuthRepository` and store it in [flutter_secure_storage](https://pub.dev/packages/flutter_secure_storage) in the form of key:value pairs, Include `userId` in key (eg: <userId>_PIN) so that it PIN's of two user's don't clash.

**Comment by abhinavs1920** [comment]
I am working on this issue, Please assign it to me.

**Comment by SankethBK** [comment]
Sure @abhinavs1920

**Comment by LujainAlMansoori** [comment]
Hello @SankethBK, could you please assign me to this, I have experience working with this feature!

**Comment by SankethBK** [comment]
Sure @LujainAlMansoori

**Comment by LujainAlMansoori** [comment]
Hey @SankethBK this has been resolved! Please check PR #161
