### ISSUE TITLE
Implement PIN based authentication - 2 

### ISSUE THREAD

**Issue by SankethBK** [SankethBK/diaryvault#72]
In first part of this [issue](https://github.com/SankethBK/diaryvault/issues/71), user enables the PIN based authentication and has setup a 4 digit PIN.

In this part we need to implement the authentication screen to collect and validate PIN during login. 

#### 1. Create a new screen to collect 4 digit PIN, (something like this, keep it consistent with themes)

<img width="315" alt="image" src="https://github.com/SankethBK/diaryvault/assets/51091231/2c4c3972-0438-4308-9771-b51c477b0f90">

If the "PIN-based authentication" is enabled, we should redirect user to PIN login screen instead of email+password login screen. 
In order to check if PIN based authentication is enabled, we need to read `userConfigModel` from shared preferences and check its `isPINLoginEnabled` (similar thing is done to check if fingerprint login is enabled, check `shouldActivateFingerPrint`)

Create `shouldredirectToPINAuthScreen` in  `PINAuthRepository` similar to `shouldActivateFingerPrint`.

#### 2. Verifying PIN and login

Create `verifyPIN` method in `PINAuthRepository`, this method should read the PIN stored in [flutter_secure_storage](https://pub.dev/packages/flutter_secure_storage) in the form of key:value pairs (key would be in the form of <user_id>_PIN) If the PIN stored in secure_storage matches the PIN entered by user,  we need to emit `UserLoggedIn` event on `authSessionBloc` to start a login session with given `user`.

**Comment by msaqeeb72** [comment]
Hey @SankethBK ,
Can you assign this to me, I have already implemented similar feature in native android.

**Comment by SankethBK** [comment]
Sure @msaqeeb72 , this depends on first part of the [issue](https://github.com/SankethBK/diaryvault/issues/71). See if you can mock / hardcode the dependant functions, till first part is completed

**Comment by msaqeeb72** [comment]
I will write UI and functions and tested it with mock pin.

**Comment by SankethBK** [comment]
Cool, that'd be great

**Comment by LujainAlMansoori** [comment]
Hello can I work on this as well please, I'm working on authentication part 1 and this would be an extension of it! Thank you

**Comment by SankethBK** [comment]
Sure @LujainAlMansoori
