### ISSUE TITLE
 Translation Contributions: Help Us Translate DiaryVault into Your Language

### ISSUE THREAD

**Issue by SankethBK** [SankethBK/diaryvault#75]
Steps

1. Get the language code for the language you want to translate from [here](https://api.flutter.dev/flutter/flutter_localizations/GlobalMaterialLocalizations-class.html). For eg: its `en` for English, `es` for Spanish, etc.
2. Create an `.arb` File: In the `lib/l10n/` directory, create a new `.arb` file named `intl_<language_code>.arb`. For eg: if you are contributing Spanish, then your filename would be `intl_es.arb`.
3. Translate Messages: Refer to the template file `intl_en.arb` as a reference. Inside this file, you will find key-value pairs where the keys should remain the same, but you should translate the corresponding values into your target language.
4. Install [Flutter-intl](https://marketplace.visualstudio.com/items?itemName=localizely.flutter-intl) VSCode extension for autogenerating files

**Comment by markandey1414** [comment]
Hello @SankethBK I would like to work on this issue

**Comment by SankethBK** [comment]
Sure @markandey1414. Please mention the language you want to add a translation for so that two people won't accidentally work on translating to the same language.

**Comment by bibekpanda55** [comment]
I can add one more language.

**Comment by SankethBK** [comment]
> I can add one more language.

@bibekpanda55 yes that would be great

**Comment by bibekpanda55** [comment]
I will add the "or - Oriya" language

**Comment by nikolai1312** [comment]
Hey, can i help with this issue? I can contribute with PT-BR translation.

**Comment by SankethBK** [comment]
Sure @nikolai1312

**Comment by markandey1414** [comment]
I can also add Punjabi - Pa to this. Should I go for it? @SankethBK

**Comment by TomerPacific** [comment]
@SankethBK - I'd like to help out by adding Hebrew - he to the translations.

**Comment by SankethBK** [comment]
Sure @TomerPacific

**Comment by MaryamMansour** [comment]
Can I help with Translation? I'd like to add Arabic

**Comment by SankethBK** [comment]
Sure @MaryamMansour

**Comment by Kundai10** [comment]
@SankethBK I would like to work on sw-Swahili

**Comment by SankethBK** [comment]
Sure @Kundai10

**Comment by 3kdeveloper** [comment]
Hello @SankethBK I would like to add Urdu to this project.

**Comment by SankethBK** [comment]
Sure @3kdeveloper

**Comment by minna-xD** [comment]
Hello! I would like to contribute a Finnish translation.

**Comment by SankethBK** [comment]
Sure @minna-xD

**Comment by 3kdeveloper** [comment]
@SankethBK Sry bro currently i am too much busy in personal projects.

**Comment by SankethBK** [comment]
@3kdeveloper no worries, this repo will remain public you can contribute whenever you're free!

**Comment by mbfannan** [comment]
Hello @SankethBK I'd like to work on the Arabic version as well.

**Comment by SankethBK** [comment]
@mbfannan Arabic translation is currently [there](https://github.com/SankethBK/diaryvault/blob/master/lib/l10n/intl_ar.arb) but its incomplete. You can add remaining values. You can refer the values from [english](https://github.com/SankethBK/diaryvault/blob/master/lib/l10n/intl_en.arb)

**Comment by zainabAhm** [comment]
Hey @SankethBK I would like to work on an italian translator!

**Comment by SankethBK** [comment]
@zainabAhm sure

**Comment by HarikaB11** [comment]
Ho @SankethBK , I would like to work on Telugu translation.

**Comment by HarikaB11** [comment]
Hi @SankethBK , I have created PR #168 which provides Telugu translation for issue #75.

**Comment by nokacper24** [comment]
Hey, I'd like to contribute by adding Polish translations. Is that okay?

**Comment by SankethBK** [comment]
@nokacper24 sure, go ahead

**Comment by marek-jakub** [comment]
Hi, I would like to add Slovak translation.

**Comment by SankethBK** [comment]
@marek-jakub sure go ahead

**Comment by marek-jakub** [comment]
Wanted to ask, been playing with the app, I really like it. After choosing a language, the messages are OK apart from the message on deleting a note, which is always in English (the one saying 'Your are about to delete {number} item). Could that be reported as an issue, or shall I leave it? Thanks.

**Comment by AliYar-Khan** [comment]
> Hello @SankethBK I would like to add Urdu to this project.

@3kdeveloper did you finished it or not ?

**Comment by huza786** [comment]
is urdu finished or can i add it
